name: webfeed
version: 0.4.2
description: webfeed is a dart package for parsing RSS and Atom feeds. Media & DublinCore namespaces are also supported.
author: Wito Chandra <wito.c.91@gmail.com>
homepage: https://github.com/witochandra/webfeed
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  xml: ^5.0.2
dev_dependencies:
  test: ^1.16.5
  http: ^0.13.0
